### ISSUE TITLE
Cache Directory Change after Low Storage on Main Disk (macOS)

### ISSUE THREAD

**Issue by HashaRock** [itsToggle/rclone_RD#11]
hello!

I was running rclone and it is doing great! It works perfectly but once I try to play a file that was scraped, it fails to cache the file. I understand that it can't find any storage and I have cleared up around 8 GBs or so. However, is there any way for me to transfer the cache folder to my external drive? Most of the files that are being played will run out of space in that case if the cache isn't deleted!

2022/08/03 22:34:06 ERROR : Little.Women.2019.2160p.BCORE.WEB-DL.x265.10bit.HDR.DTS-HD.MA.5.1-SWTYBLZ.mkv/Little.Women.2019.2160p.BCORE.WEB-DL.x265.10bit.HDR.DTS-HD.MA.5.1-SWTYBLZ.mkv: vfs cache: failed to download: vfs reader: failed to write to cache file: write /Users/hassaanali/Library/Caches/rclone/vfs/HashaRockRD/Little.Women.2019.2160p.BCORE.WEB-DL.x265.10bit.HDR.DTS-HD.MA.5.1-SWTYBLZ.mkv/Little.Women.2019.2160p.BCORE.WEB-DL.x265.10bit.HDR.DTS-HD.MA.5.1-SWTYBLZ.mkv: no space left on device
2022/08/03 22:34:06 ERROR : Little.Women.2019.2160p.BCORE.WEB-DL.x265.10bit.HDR.DTS-HD.MA.5.1-SWTYBLZ.mkv/Little.Women.2019.2160p.BCORE.WEB-DL.x265.10bit.HDR.DTS-HD.MA.5.1-SWTYBLZ.mkv: vfs cache: cache is out of space 1/10: last error: vfs reader: failed to write to cache file: write /Users/hassaanali/Library/Caches/rclone/vfs/HashaRockRD/Little.Women.2019.2160p.BCORE.WEB-DL.x265.10bit.HDR.DTS-HD.MA.5.1-SWTYBLZ.mkv/Little.Women.2019.2160p.BCORE.WEB-DL.x265.10bit.HDR.DTS-HD.MA.5.1-SWTYBLZ.mkv: no space left on device
2022/08/03 22:34:06 ERROR : Little.Women.2019.2160p.BCORE.WEB-DL.x265.10bit.HDR.DTS-HD.MA.5.1-SWTYBLZ.mkv/Little.Women.2019.2160p.BCORE.WEB-DL.x265.10bit.HDR.DTS-HD.MA.5.1-SWTYBLZ.mkv: vfs cache: failed to kick waiters: vfs reader: failed to write to cache file: write /Users/hassaanali/Library/Caches/rclone/vfs/HashaRockRD/Little.Women.2019.2160p.BCORE.WEB-DL.x265.10bit.HDR.DTS-HD.MA.5.1-SWTYBLZ.mkv/Little.Women.2019.2160p.BCORE.WEB-DL.x265.10bit.HDR.DTS-HD.MA.5.1-SWTYBLZ.mkv: no space left on device
2022/08/03 22:34:06 ERROR : Little.Women.2019.2160p.BCORE.WEB-DL.x265.10bit.HDR.DTS-HD.MA.5.1-SWTYBLZ.mkv/Little.Women.2019.2160p.BCORE.WEB-DL.x265.10bit.HDR.DTS-HD.MA.5.1-SWTYBLZ.mkv: vfs cache: failed to _ensure cache vfs reader: failed to write to cache file: write /Users/hassaanali/Library/Caches/rclone/vfs/HashaRockRD/Little.Women.2019.2160p.BCORE.WEB-DL.x265.10bit.HDR.DTS-HD.MA.5.1-SWTYBLZ.mkv/Little.Women.2019.2160p.BCORE.WEB-DL.x265.10bit.HDR.DTS-HD.MA.5.1-SWTYBLZ.mkv: no space left on device
2022/08/03 22:34:06 NOTICE: vfs cache: in KickCleaner, ready to kick cleaner
^[[A^[[A^[[B^[[B^C2022/08/04 09:00:16 ERROR : /Users/hassaanali/HashaRock_RD: Unmounted rclone mount

**Comment by itsToggle** [comment]
Hey, sorry for the late response.

You can change the cache directory and limit the cache directories maximum size. Check the official rclone documentation :)
