### ISSUE TITLE
[DOCUMENTATION] : Guidance on installing Rclone Fork on Ubuntu with Arm-based processor 🥇 

### ISSUE THREAD

**Issue by dspdhckr** [itsToggle/rclone_RD#12]
Hey there,

Could I get the installation steps for Ubuntu to use your fork. I know very naive question but I tried and tested many times but was unable to install it on my Ubuntu server as I am not able to see the file extension so not aware how to install it. Please if you can guide me to install it on my server would be greatly appreciated.

**Comment by dspdhckr** [comment]
Meanwhile I am using Rclone official fork but I do really want to delete watched torrents and likewise from my Real-Debrid and scanning of already downloaded content is taking up lot of resources on my server.

**Comment by itsToggle** [comment]
Hey,

I've pre-built the latest arm version with the following parameters:

    GOOS=linux GOARCH=arm GOARM=5

If that fits your server, you can download this release by running:

    wget https://github.com/itsToggle/rclone_RD/releases/download/v1.58.1-rd.1.5/rclone-linux-arm

Once downloaded, you can make it executable by running:

    sudo chmod u+x rclone-linux-arm

after that run:

    sudo rclone-linux-arm config

If that last command fails because of "command unknown", try running:

    sudo ./rclone-linux-arm config

**Comment by dspdhckr** [comment]
Hey there, you are a life saver. I am able to run your rclone version on my Ubuntu server based on armv8 and working completely fine. I was going through one line from the plex_debrid link for in depth documentation and found that real-debrid does have 200 torrent limits and the issue with it is that there were some TV shows which I was watching and it was showing an error that the file is not available. I am just wondering whether I am doing it right or not because while setting up official rclone I had setup the webdav using credentials from my account of Real-Debrid. But thought to reset it completely. As you are saying there are some limitations of official webdrive so shall I use those username and password for webdav from my account or the real-debrid account username and password. Also, can you elaborate what is the difference between my downloads and torrents section? I assume my downloads under my account settings refer to cached torrents we have and my torrents are the uncached torrent right? Because I usually delete the download history from my account as real-debrid exposes my server IP there which I don't want. Keeping torrents but clearning my downloads list will have some adverse on my plex library?

**Comment by dspdhckr** [comment]
Thank you so much for all the support. All doubts resolved. You are a legend. Keep this good work coming please.

**Comment by dspdhckr** [comment]
Hey there I have installed your fork but it is showing me an error that rclone command not found. Am I doing something wrong here? Also, to mention, to install your fork, I had deleted the previous official rclone files. Is that the reason?

**Comment by itsToggle** [comment]
you just need to adjust "rclone" to "rclone-linux-arm" I think. To setup a new remote, run:

    ./rclone-linux-arm config

To mount your remote, run:

    sudo ./rclone-linux mount your-remote: some/folder--dir-cache-time 10s --vfs-cache-mode full --allow-other --daemon

**Comment by itsToggle** [comment]
Are you opening the terminal in the location of the "rclone-linux-arm" file?

**Comment by dspdhckr** [comment]
Hey yes so I tried the command you sent and yes it worked when I cd to the location where the file is located.

sudo ./rclone-linux-arm mount Plex: /mnt/Plex --vfs-cache-mode full --dir-cache-time=10s --allow-non-empty --allow-other --daemon

This is the command I used. 

Also, successful creation of all directories are here. Will setup above command to be executed when the system reboots.

<img width="1512" alt="Screenshot 2022-08-23 at 21 53 34" src="https://user-images.githubusercontent.com/75004469/186263583-1dfe4a9d-f47a-46b6-ad5a-e7fd46695327.png">

Let me check this and I guess this should work fine. Thanks for the quick answers by the way! You are a legend. I hope you continue develop the arm version as well in the future if any.

**Comment by dspdhckr** [comment]
<img width="1512" alt="Screenshot 2022-08-23 at 21 59 23" src="https://user-images.githubusercontent.com/75004469/186264466-cd6bc94d-a6a5-4728-9097-e58f1a0c575e.png">

This is the shell script I have been using on reboot or boot so that all relevant scripts would start working after reboot. I have commented some traktsync here because I am testing this new rclone fork but those are usually on production.

**Comment by itsToggle** [comment]
Hey, I've deleted your last comment, as the editing history is visible on github. For future reference, there was personal information visible in this comment.
Let me know how the rest goes :)

**Comment by dspdhckr** [comment]
Thank you so much! Much apprecieated!
