### ISSUE TITLE
Ability to move files from movies to shows ? 
Some animes are downloaded to movies folder is there anyway to sort it back to shows ? 

### ISSUE THREAD

**Issue by krishne35** [itsToggle/rclone_RD#18]
#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by itsToggle** [comment]
Hey, this is currently not possible. Would you mind telling me the torrents tile? You can of course simply add both the "shows" and the "movies" folder to your shows library.

**Comment by itsToggle** [comment]
Yeah its not possible to categorize this as a show automatically, since there is no "SXX", "SXXEXX" or "COMPLETE" tag to the torrents tile.

**Comment by krishne35** [comment]
If Im not wrong the rclone_rd doesn't actually create movies/ shows/ on real debrid cloud but just sorts it while mounting right ?

If so can you make it such that it prints out a config file in which it will show where it gonna place the files and we can modify that config file to sort manually

**Comment by itsToggle** [comment]
That is correct. I could make the regex definition editable in the advanced settings during the rclone_rd setup. This will also allow you to to edit these definitions inside the rclone config file.

What you could also do is filter rclone yourself. Rclone has a wonderful feature called "--filter", which allows you to filter out any unwanted files or create a 4k and a 1080p library. You can find the documentation for this on the official rclone resources.

**Comment by philamp** [comment]
I'd like to ask for something a little bit more ambitious : the ability to sort files in folders and subfolders given a list of 
*source paths -> target paths*, 
plain/defaut/path -> strutured/path/file.mp4
example:
/shows/tvshow.s02e01/episode01.mp4 -> /Library/shows/tvshow/s02/episodes02e01.mp4

Would it be possible ?

The purpose is to sort these files following the plex library sorting

Its basically a way to leverage plex sorting to make the folder sorting cleaner for direct browsing
