### ISSUE TITLE
Folder sorting disable

### ISSUE THREAD

**Issue by jordanshaikly** [itsToggle/rclone_RD#23]
Hi,

Currently using your fork but RD seems to be incorrectly sorting downloaded items into the wrong folders, e.g. movie and shows.
Is there a way to disable these folders altogether so this doesn't occur?

**Comment by itsToggle** [comment]
Hey, you can edit how the sorting is done by going into the advanced config (run "rclone config" and edit your realdebrid remote).
If you don't want any sorting at all, you could either tell your personal media server to look for movies and shows in all folders, or you could go into the advanced config of your remote and change the "folder_mode" to "files", which will simply display all files in the root folder.
