### ISSUE TITLE
fuse: panic in handler for Lookup

### ISSUE THREAD

**Issue by maxexcloo** [itsToggle/rclone_RD#28]
#### What is the problem you are having with rclone?

When mounting occasionally rclone will spit out the error shown below, aside from this everything seems to be working okay. Happy to provide any more information or debug assistance 👍🏻 Also, thank you for this project - amazing stuff!

#### What is your rclone version?

```
maxexcloo@server:~$ rclone_rd version
rclone v1.59.0-DEV
- os/version: debian 10.13 (64 bit)
- os/kernel: 5.10.0-0.deb10.19-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.18.1
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits?

```
maxexcloo@server:~$ uname -a
Linux bedok 5.10.0-0.deb10.19-amd64 #1 SMP Debian 5.10.149-2~deb10u1 (2022-10-28) x86_64 GNU/Linux
```

#### Which cloud storage system are you using?

`realdebrid`

#### The command you were trying to run?

`~/bin/rclone_rd mount realdebrid: ~/realdebrid --config ~/.config/rclone_rd/rclone_rd.conf --dir-cache-time 10s --use-mmap --vfs-cache-mode full`

#### What's the error?

```
Jan 10 03:03:33 bedok rclone_rd[2500600]: fuse: panic in handler for Lookup [ID=0x28d6 Node=0x1 Uid=1004 Gid=1004 Pid=939655] "shows": runtime error: invalid memory address or nil pointer dereference
Jan 10 03:03:33 bedok rclone_rd[2500600]: goroutine 6380 [running]:
Jan 10 03:03:33 bedok rclone_rd[2500600]: bazil.org/fuse/fs.(*Server).serve.func2()
Jan 10 03:03:33 bedok rclone_rd[2500600]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:994 +0x14e
Jan 10 03:03:33 bedok rclone_rd[2500600]: panic({0x18b6ca0, 0x2d489a0})
Jan 10 03:03:33 bedok rclone_rd[2500600]:         C:/Program Files/Go/src/runtime/panic.go:838 +0x207
Jan 10 03:03:33 bedok rclone_rd[2500600]: github.com/rclone/rclone/backend/realdebrid.(*Fs).listAll(0xc000459a40, {0x2020be8?, 0xc000116008}, {0x1bc2e1f, 0x1}, 0x0, 0x0, 0xc00053d6b0)
Jan 10 03:03:33 bedok rclone_rd[2500600]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD/backend/realdebrid/realdebrid.go:530 +0x3d43
Jan 10 03:03:33 bedok rclone_rd[2500600]: github.com/rclone/rclone/backend/realdebrid.(*Fs).List(0xc000459a40, {0x2020be8, 0xc000116008}, {0x0, 0x0})
Jan 10 03:03:33 bedok rclone_rd[2500600]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD/backend/realdebrid/realdebrid.go:828 +0x125
Jan 10 03:03:33 bedok rclone_rd[2500600]: github.com/rclone/rclone/fs/list.DirSorted({0x2020be8, 0xc000116008}, {0x2030e28?, 0xc000459a40?}, 0x0, {0x0, 0x0})
Jan 10 03:03:33 bedok rclone_rd[2500600]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD/fs/list/list.go:24 +0x83
Jan 10 03:03:33 bedok rclone_rd[2500600]: github.com/rclone/rclone/vfs.(*Dir)._readDir(0xc00027c0c0)
Jan 10 03:03:33 bedok rclone_rd[2500600]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD/vfs/dir.go:453 +0x11b
Jan 10 03:03:33 bedok rclone_rd[2500600]: github.com/rclone/rclone/vfs.(*Dir).stat(0xc00027c0c0, {0xc0006c6010, 0x5})
Jan 10 03:03:33 bedok rclone_rd[2500600]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD/vfs/dir.go:702 +0xbb
Jan 10 03:03:33 bedok rclone_rd[2500600]: github.com/rclone/rclone/vfs.(*Dir).Stat(0x1bb40e0?, {0xc0006c6010?, 0x1bcac20?})
Jan 10 03:03:33 bedok rclone_rd[2500600]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD/vfs/dir.go:799 +0x27
Jan 10 03:03:33 bedok rclone_rd[2500600]: github.com/rclone/rclone/cmd/mount.(*Dir).Lookup(0xc00018a9b0, {0x200fbe0?, 0xc00018a9b0?}, 0xc00012a380, 0xc00027c180)
Jan 10 03:03:33 bedok rclone_rd[2500600]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD/cmd/mount/dir.go:77 +0x188
Jan 10 03:03:33 bedok rclone_rd[2500600]: bazil.org/fuse/fs.(*Server).handleRequest(0xc00093a000, {0x2020bb0, 0xc000a54180}, {0x200fbe0?, 0xc00018a9b0}, 0xc00038a7c0, {0x201b200?, 0xc00012a380?}, 0xc00053df08)
Jan 10 03:03:33 bedok rclone_rd[2500600]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:1187 +0x27fe
Jan 10 03:03:33 bedok rclone_rd[2500600]: bazil.org/fuse/fs.(*Server).serve(0xc00093a000, {0x201b200, 0xc00012a380})
Jan 10 03:03:33 bedok rclone_rd[2500600]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:1015 +0x634
Jan 10 03:03:33 bedok rclone_rd[2500600]: bazil.org/fuse/fs.(*Server).Serve.func1()
Jan 10 03:03:33 bedok rclone_rd[2500600]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:512 +0x69
Jan 10 03:03:33 bedok rclone_rd[2500600]: created by bazil.org/fuse/fs.(*Server).Serve
Jan 10 03:03:33 bedok rclone_rd[2500600]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:510 +0x3be
```

**Comment by maxexcloo** [comment]
I should note that I am running this through a https://github.com/ivoronin/wiresocks SOCKS5 proxy.

**Comment by maxexcloo** [comment]
```Jan 19 09:00:12 bedok rclone_rd[1679850]: fuse: panic in handler for Read [ID=0x1f8f8 Node=0xacf Uid=1004 Gid=1004 Pid=2207766] 0x5 4096 @0x0 dir=true fl=0 owner=0 ffl=OpenReadOnly+OpenDirectory: runtime error: invalid memory address or nil pointer dereference
Jan 19 09:00:12 bedok rclone_rd[1679850]: goroutine 64494 [running]:
Jan 19 09:00:12 bedok rclone_rd[1679850]: bazil.org/fuse/fs.(*Server).serve.func2()
Jan 19 09:00:12 bedok rclone_rd[1679850]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:994 +0x14e
Jan 19 09:00:12 bedok rclone_rd[1679850]: panic({0x18b6ca0, 0x2d49920})
Jan 19 09:00:12 bedok rclone_rd[1679850]:         C:/Program Files/Go/src/runtime/panic.go:838 +0x207
Jan 19 09:00:12 bedok rclone_rd[1679850]: github.com/rclone/rclone/backend/realdebrid.(*Fs).listAll(0xc000e7cb40, {0x2020c68?, 0xc000052080}, {0xc000b16be0, 0xd}, 0x0, 0x0, 0xc0006296d0)
Jan 19 09:00:12 bedok rclone_rd[1679850]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/backend/realdebrid/realdebrid.go:696 +0x16f2
Jan 19 09:00:12 bedok rclone_rd[1679850]: github.com/rclone/rclone/backend/realdebrid.(*Fs).List(0xc000e7cb40, {0x2020c68, 0xc000052080}, {0xc0004f2c90, 0x2d})
Jan 19 09:00:12 bedok rclone_rd[1679850]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/backend/realdebrid/realdebrid.go:828 +0x125
Jan 19 09:00:12 bedok rclone_rd[1679850]: github.com/rclone/rclone/fs/list.DirSorted({0x2020c68, 0xc000052080}, {0x2030ea8?, 0xc000e7cb40?}, 0x0, {0xc0004f2c90, 0x2d})
Jan 19 09:00:12 bedok rclone_rd[1679850]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/fs/list/list.go:24 +0x83
Jan 19 09:00:12 bedok rclone_rd[1679850]: github.com/rclone/rclone/vfs.(*Dir)._readDir(0xc001756cc0)
Jan 19 09:00:12 bedok rclone_rd[1679850]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/vfs/dir.go:453 +0x11b
Jan 19 09:00:12 bedok rclone_rd[1679850]: github.com/rclone/rclone/vfs.(*Dir).ReadDirAll(0xc001756cc0)
Jan 19 09:00:12 bedok rclone_rd[1679850]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/vfs/dir.go:814 +0x54
Jan 19 09:00:12 bedok rclone_rd[1679850]: github.com/rclone/rclone/cmd/mount.(*Dir).ReadDirAll(0xc003133b60, {0x1bb40e0?, 0xc003133b60?})
Jan 19 09:00:12 bedok rclone_rd[1679850]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD-master/cmd/mount/dir.go:108 +0x14a
Jan 19 09:00:12 bedok rclone_rd[1679850]: bazil.org/fuse/fs.(*Server).handleRequest(0xc0000381c0, {0x2020c30, 0xc0032aa040}, {0x200fc60?, 0xc003133b60}, 0xc000547a40, {0x201b3d0?, 0xc000de8070?}, 0xc000629f08)
Jan 19 09:00:12 bedok rclone_rd[1679850]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:1378 +0xb57
Jan 19 09:00:12 bedok rclone_rd[1679850]: bazil.org/fuse/fs.(*Server).serve(0xc0000381c0, {0x201b3d0, 0xc000de8070})
Jan 19 09:00:12 bedok rclone_rd[1679850]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:1015 +0x634
Jan 19 09:00:12 bedok rclone_rd[1679850]: bazil.org/fuse/fs.(*Server).Serve.func1()
Jan 19 09:00:12 bedok rclone_rd[1679850]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:512 +0x69
Jan 19 09:00:12 bedok rclone_rd[1679850]: created by bazil.org/fuse/fs.(*Server).Serve
Jan 19 09:00:12 bedok rclone_rd[1679850]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:510 +0x3be```

Another error today...

**Comment by itsToggle** [comment]
> I occasionally run into the same problem
> 
> ```
> Jan 08 11:53:05 REDACTED rclone-linux[22247]: fuse: panic in handler for Lookup [ID=0x1da182c0 Node=0x85d Uid=0 Gid=0 Pid=521656] ".plexmatch": runtime error: invalid memory address or nil pointer dereference
> Jan 08 11:53:05 REDACTED rclone-linux[22247]: goroutine 250904903 [running]:
> Jan 08 11:53:05 REDACTED rclone-linux[22247]: bazil.org/fuse/fs.(*Server).serve.func2()
> Jan 08 11:53:05 REDACTED rclone-linux[22247]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:994 +0x14e
> Jan 08 11:53:05 REDACTED rclone-linux[22247]: panic({0x18b6ca0, 0x2d489a0})
> Jan 08 11:53:05 REDACTED rclone-linux[22247]:         C:/Program Files/Go/src/runtime/panic.go:838 +0x207
> Jan 08 11:53:05 REDACTED rclone-linux[22247]: github.com/rclone/rclone/backend/realdebrid.(*Fs).listAll(0xc000974e60, {0x2020be8?, 0xc0000c0008}, {0xc000558ce0, 0xd}, 0x0, 0x0, 0xc000a3d6b0)
> Jan 08 11:53:05 REDACTED rclone-linux[22247]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD/backend/realdebrid/realdebrid.go:696 +0x16f2
> Jan 08 11:53:05 REDACTED rclone-linux[22247]: github.com/rclone/rclone/backend/realdebrid.(*Fs).List(0xc000974e60, {0x2020be8, 0xc0000c0008}, {0xc001e05bc0, 0x58})
> Jan 08 11:53:05 REDACTED rclone-linux[22247]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD/backend/realdebrid/realdebrid.go:828 +0x125
> Jan 08 11:53:05 REDACTED rclone-linux[22247]: github.com/rclone/rclone/fs/list.DirSorted({0x2020be8, 0xc0000c0008}, {0x2030e28?, 0xc000974e60?}, 0x0, {0xc001e05bc0, 0x58})
> Jan 08 11:53:05 REDACTED rclone-linux[22247]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD/fs/list/list.go:24 +0x83
> Jan 08 11:53:05 REDACTED rclone-linux[22247]: github.com/rclone/rclone/vfs.(*Dir)._readDir(0xc001c11080)
> Jan 08 11:53:05 REDACTED rclone-linux[22247]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD/vfs/dir.go:453 +0x11b
> Jan 08 11:53:05 REDACTED rclone-linux[22247]: github.com/rclone/rclone/vfs.(*Dir).stat(0xc001c11080, {0xc000dbc070, 0xa})
> Jan 08 11:53:05 REDACTED rclone-linux[22247]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD/vfs/dir.go:702 +0xbb
> Jan 08 11:53:05 REDACTED rclone-linux[22247]: github.com/rclone/rclone/vfs.(*Dir).Stat(0x1bb40e0?, {0xc000dbc070?, 0x1bcac20?})
> Jan 08 11:53:05 REDACTED rclone-linux[22247]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD/vfs/dir.go:799 +0x27
> Jan 08 11:53:05 REDACTED rclone-linux[22247]: github.com/rclone/rclone/cmd/mount.(*Dir).Lookup(0xc001339f30, {0x200fbe0?, 0xc001339f30?}, 0xc003455940, 0xc000756900)
> Jan 08 11:53:05 REDACTED rclone-linux[22247]:         C:/Users/Ronald/Desktop/ttrd/rclone_RD/rclone_RD/cmd/mount/dir.go:77 +0x188
> Jan 08 11:53:05 REDACTED rclone-linux[22247]: bazil.org/fuse/fs.(*Server).handleRequest(0xc0009e0000, {0x2020bb0, 0xc0036d3180}, {0x200fbe0?, 0xc001339f30}, 0xc001346200, {0x201b200?, 0xc003455940?}, 0xc000a3df08)
> Jan 08 11:53:05 REDACTED rclone-linux[22247]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:1187 +0x27fe
> Jan 08 11:53:05 REDACTED rclone-linux[22247]: bazil.org/fuse/fs.(*Server).serve(0xc0009e0000, {0x201b200, 0xc003455940})
> Jan 08 11:53:05 REDACTED rclone-linux[22247]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:1015 +0x634
> Jan 08 11:53:05 REDACTED rclone-linux[22247]: bazil.org/fuse/fs.(*Server).Serve.func1()
> Jan 08 11:53:05 REDACTED rclone-linux[22247]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:512 +0x69
> Jan 08 11:53:05 REDACTED rclone-linux[22247]: created by bazil.org/fuse/fs.(*Server).Serve
> Jan 08 11:53:05 REDACTED rclone-linux[22247]:         C:/Users/Ronald/go/pkg/mod/bazil.org/fuse@v0.0.0-20200524192727-fb710f7dfd05/fs/serve.go:510 +0x3be
> ```

This is a different issue, sounds like you are attempting to upload a ".plexmatch" file to realdebrid. Realdebrid is a read-only remote, except that removing content is possible. Uploading does not and will never work.

**Comment by itsToggle** [comment]
These memory panics happen because Im accessing the response status code. Apparently GO does not always return a status code, so I need to try and catch these bits.
