### ISSUE TITLE
Issue with the recoded and optimised versions of Plex

### ISSUE THREAD

**Issue by ghost** [itsToggle/rclone_RD#35]
Hi there, 

Please tell me how to avoid this thing. I have attached the screenshot here. There is an issue with the optimised versions I made and I am not able to get the rclone to run on my server since then. I have deleted all my media from RealDebrid and changed the Plex Media library to an empty folder now.
 
<img width="1512" alt="Screenshot 2023-04-18 at 18 09 20" src="https://user-images.githubusercontent.com/118989300/232855684-13bcbe16-d422-4e8d-a810-f26c2916ce9d.png">

**Comment by itsToggle** [comment]
Hi, plex would try to "upload" these to your mounted drive, which is not possible.
You will need to empty your vfs cache directory (a quick google search should help you find it)
You cannot optimize your library using the read-only realdebrid mount.

**Comment by ghost** [comment]
Hey, I tried demounting and mounting again, and then after that, I restarted my server quite a few times but no luck. I need help finding the VFS cache directory, as suggested by you for Ubuntu on Google. Please guide me on how to do it or at least remove the optimised version, as I can't see any single optimised version on the Plex Server side.

**Comment by itsToggle** [comment]
Should be visible using `cd .cache`
If not, here's how you can find it:
https://forum.rclone.org/t/whats-the-default-vfs-cache-directory-of-rclone-for-linux/26063

**Comment by itsToggle** [comment]
So it should be `.cache/rclone/vfs`

**Comment by itsToggle** [comment]
Just delete the contents of that folder and re-mount. that should do the trick. Obviously disable any "optimization" settings in Plex.

**Comment by ghost** [comment]
Hey there, I cleared that folder and tried remounting the drive after a full server restart. but still no luck.

**Comment by ghost** [comment]
Still it is showing the same error and there are no optimisations currently running for that matter.

**Comment by ghost** [comment]
Here is the screenshot of the same, I am trying the following command btw
`sudo ./rclone-linux-arm64 mount RD: /mnt/RD --dir-cache-time 10s --allow-non-empty --vfs-cache-mode full --allow-other --daemon`

<img width="567" alt="Screenshot 2023-04-19 at 16 06 04" src="https://user-images.githubusercontent.com/118989300/233118926-471b8592-481c-4810-8970-a92865015588.png">

**Comment by itsToggle** [comment]
alright there is still a missmatch between the folder structure in your vfs cache and on the actual remote. You are mounting with sudo - is your current user root? If not, please switch to root and repeat:
- log in as root
- unmount
- disable any plex optimization settings
- delete the contents of `.cache/rclone/vfs`
- remount

if that still doesnt work, you can specify a new vfs-cache directory using `--cache-dir a/different/directory`

**Comment by ghost** [comment]
I am logging in only with the root username, but I am getting additional privileges by going to superuser mode. I am now only able to see the following directory structure.

<img width="1197" alt="Screenshot 2023-04-19 at 16 21 59" src="https://user-images.githubusercontent.com/118989300/233123470-7ffd8b7c-83d8-4082-89c4-595f8ead8ce8.png">

All my optimisations are stopped, and I have deleted all content from my Real Debrid. I deleted the host from the setting and added Real Debrid again by refreshing the API key too! Still needs to be fixed.

<img width="1491" alt="Screenshot 2023-04-19 at 16 23 40" src="https://user-images.githubusercontent.com/118989300/233124042-7d3a2de2-9cee-4a8f-bff8-0f8f524c3dd8.png">

<img width="1503" alt="Screenshot 2023-04-19 at 16 23 55" src="https://user-images.githubusercontent.com/118989300/233124082-0dd9417b-5111-478b-99d9-be5f78cf5f8f.png">

**Comment by itsToggle** [comment]
I didnt write "stop your conversions". I ment "disable all settings related to optimization". 

I want you to delete the .cache/rclone/vfs folder for the root user, not the ubuntu user like it's shown in your screenshot

**Comment by itsToggle** [comment]
![Screenshot_20230420-093425](https://user-images.githubusercontent.com/71379623/233293894-d907cf10-7459-4d85-af52-c41c41483320.png)

**Comment by itsToggle** [comment]
I've also given you another possible solution. Please try this as well:

"if that still doesnt work, you can specify a new vfs-cache directory using --cache-dir a/different/directory"

**Comment by ghost** [comment]
Hey,

Sorry, I couldn't check the solution you provided yesterday. I did try this morning, and what I did was I freshly installed Plex on my server and changed the cache directory. I could not log in to Root user due to some server constraint. Nevertheless, I have now resolved the issue, and thank you again for all your support during my hard time!
