### ISSUE TITLE
Fuse Device Not Found?

### ISSUE THREAD

**Issue by Spectre216** [itsToggle/rclone_RD#37]
So did a fresh setup following the direction here on the wiki, but when I run  ./rclone-linux mount realdebrid: torrents --dir-cache-time=10s --allowothers

I get the following error

2023/06/09 17:56:36 mount helper error: fusermount: fuse device not found, try 'modprobe fuse' first
2023/06/09 17:56:36 Fatal error: failed to mount FUSE fs: fusermount: exit status 1

Wondering if this is because my Plex server (with the plexdebrid script) is hosted in an Ubuntu container on Proxmox instead of a full VM? It is privileged, so I can mount all of my SMB shares no problem, but maybe I need to do something additional?

Any thoughts?

**Comment by cjgochanour** [comment]
I had the same problem.

In Proxmox, click your container => options => features => make sure FUSE is checked.
