### ISSUE TITLE
Support for alldebrid

### ISSUE THREAD

**Issue by progamerz02** [itsToggle/rclone_RD#5]
Is it possible in the near future to have something like this for alldebrid?

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by itsToggle** [comment]
I dont have an AllDebrid account, so I wont be able to assist you. You or someone else can feel free to fork rclone and change the code of an existing backend to work with AllDebrid, much like I did for RealDebrid. Its not a lot of code that needs changing :)

**Comment by itsToggle** [comment]
Hey, as Ive learned AllDebrid has a WebDav server (https://alldebrid.com/help/en/Alldebrid%20tools/webdav). You can mount this webdav server as a virtual drive using the official rclone software!
