### ISSUE TITLE
Rclone Mount Windows

### ISSUE THREAD

**Issue by Dexxa1024** [itsToggle/rclone_RD#7]
Trying to get rclone to mount but cant seem to get it to mount.

Did did a new connection and added my real d api key in  and it seemed to have worked, But trying to get it to mount as a drive on windows using rclone cmount dex: v

I have added a picture, the right hand side box on the picture is rclone
![plex1](https://user-images.githubusercontent.com/11196220/169695745-9cabbd06-e31a-4a39-b501-32ada1cddb94.png)

**Comment by itsToggle** [comment]
add ':' at the end of your drive letter, e.g.: 'rclone cmount dex: V:'

**Comment by Dexxa1024** [comment]
That worked, cant beleive i forgot the :   the folder showed up in downloads but was very slow and kept vanishing, now theres a drive its working great :-D

**Comment by itsToggle** [comment]
nice! Make sure you use the recommended mounting tags to make the virtual drive a bit faster and react to changes quicker:

rclone cmount dex: V: --vfs-cache-mode=full --dir-cache-time=10s
